config/routes.rb
FaimsWeb::Application.routes.draw do
  devise_for :users, controllers: {passwords: 'user_passwords'}
  devise_scope :user do
    get '/users/profile', :to => 'user_registers#profile'
    get '/users/edit', :to => 'user_registers#edit'
    put '/users/update', :to => 'user_registers#update'
    get '/users/edit_password', :to => 'user_registers#edit_password' #allow users to edit their own password
    put '/users/update_password', :to => 'user_registers#update_password' #allow users to edit their own password
    get '/users/password/forgot', :to => 'user_passwords#forgot_password', :as => 'forgot_user_password'
  end

  resources :users, :only => [:show, :new, :create, :destroy] do

    collection do
      get :index
    end

    member do
      get :edit_role
      put :update_role
      get :edit_details
      put :update_details
      get :change_password
      put :save_password
    end
  end

  get 'project_modules', :to => 'project_modules#index', :as => 'project_modules'
  post 'project_modules', :to => 'project_modules#create', :as => 'project_modules'
  get 'project_modules/new', :to => 'project_modules#new', :as => 'new_project_module'
  get 'project_modules/upload_project_module', :to => 'project_modules#upload_project_module', :as => 'upload_project_module'
  post 'project_modules/upload_new_project_module', :to => 'project_modules#upload_new_project_module', :as => 'upload_new_project_module'
  get 'project_modules/deleted', :to => 'project_modules#list_deleted_modules', :as => 'list_deleted_modules'
  post 'project_modules/restore', :to => 'project_modules#restore_project_module', :as => 'restore_project_module'
  get 'project_modules/:id', :to => 'project_modules#show', :as => 'project_module'

  get 'project_modules/:id/edit_project_module', :to => 'project_modules#edit_project_module', :as => 'edit_project_module'
  post 'project_modules/:id/update_project_module', :to => 'project_modules#update_project_module', :as => 'update_project_module'
  delete 'project_modules/:id/delete_project_module', :to => 'project_modules#delete_project_module', :as => 'delete_project_module'

  get 'project_modules/:id/archive_project_module', :to => 'project_modules#archive_project_module', :as => 'archive_project_module'
  get 'project_modules/:id/download_project_module', :to => 'project_modules#download_project_module', :as => 'download_project_module'
  get 'project_modules/:id/check_archive_status', :to => 'project_modules#check_archive_status', :as => 'check_archive_status'
  get 'project_modules/:id/export_project_module', :to => 'project_modules#export_project_module', :as => 'export_project_module'
  post 'project_modules/:id/export_project_module', :to => 'project_modules#run_export_project_module', :as => 'run_export_project_module'
  get 'project_modules/:id/check_export_status', :to => 'project_modules#check_export_status', :as => 'check_export_status'
  get 'project_modules/:id/export_project_module/results', :to => 'project_modules#show_export_results', :as => 'show_export_results'
  get 'project_modules/:id/export_project_module/results/download_file', :to => 'project_modules#download_export_file', :as => 'download_export_file'

  get 'project_modules/:id/download_attached_file', :to => 'project_modules#download_attached_file', :as => 'download_attached_file'

  get 'project_modules/:id/file_list', :to => 'project_module_file#file_list', :as => 'project_module_file_list'
  get 'project_modules/:id/download_file', :to => 'project_module_file#download_file', :as => 'download_project_module_file'
  post 'project_modules/:id/upload_file', :to => 'project_module_file#upload_file', :as => 'upload_project_module_file'
  post 'project_modules/:id/create_dir', :to => 'project_module_file#create_dir', :as => 'project_module_create_dir'
  match 'project_modules/:id/delete_file', :to => 'project_module_file#delete_file', :as => 'delete_project_module_file'
  post 'project_modules/:id/batch_upload_file', :to => 'project_module_file#batch_upload_file', :as => 'batch_upload_file'

  get 'project_modules/:id/search_arch_ent_records/', :to => 'project_module_entity#search_arch_ent_records', :as => 'search_arch_ent_records'
  get 'project_modules/:id/delete_arch_ent_records/:uuid', :to => 'project_module_entity#delete_arch_ent_records', :as => 'delete_arch_ent_records'
  get 'project_modules/:id/restore_arch_ent_records/:uuid', :to => 'project_module_entity#restore_arch_ent_records', :as => 'restore_arch_ent_records'
  get 'project_modules/:id/edit_arch_ent_records/:uuid', :to => 'project_module_entity#edit_arch_ent_records', :as => 'edit_arch_ent_records'
  get 'project_modules/:id/get_arch_ent_record_data/:uuid', :to => 'project_module_entity#get_arch_ent_record_data', :as => 'get_arch_ent_record_data'
  post 'project_modules/:id/upload_arch_ent_attribute_file/:uuid', :to => 'project_module_entity#upload_arch_ent_attribute_file', :as => 'upload_arch_ent_attribute_file'
  post 'project_modules/:id/batch_edit_arch_ent_records/:uuid', :to => 'project_module_entity#batch_update_arch_ent_records', :as => 'batch_update_arch_ent_records'
  post 'project_modules/:id/batch_delete_related_ents/:uuid', :to => 'project_module_entity#batch_delete_related_ents', :as => 'batch_delete_related_ents'
  post 'project_modules/:id/batch_restore_related_ents/:uuid', :to => 'project_module_entity#batch_restore_related_ents', :as => 'batch_restore_related_ents'
  get 'project_modules/:id/show_arch_ent_history/:uuid', :to => 'project_module_entity#show_arch_ent_history', :as => 'show_arch_ent_history'
  post 'project_modules/:id/revert_arch_ent_to_timestamp/:uuid', :to => 'project_module_entity#revert_arch_ent_to_timestamp', :as => 'revert_arch_ent_to_timestamp'
  get 'project_modules/:id/compare_arch_ents', :to => 'project_module_entity#compare_arch_ents', :as => 'compare_arch_ents'
  post 'project_modules/:id/batch_delete_arch_ents', :to => 'project_module_entity#batch_delete_arch_ents', :as => 'batch_delete_arch_ents'
  post 'project_modules/:id/batch_restore_arch_ents', :to => 'project_module_entity#batch_restore_arch_ents', :as => 'batch_restore_arch_ents'
  post 'project_modules/:id/merge_arch_ents', :to => 'project_module_entity#merge_arch_ents', :as => 'merge_arch_ents'

  get 'project_modules/:id/list_attributes_with_vocab', :to => 'project_module_vocabulary#list_attributes_with_vocab', :as => 'list_attributes_with_vocab'
  post 'project_modules/:id/update_attributes_vocab', :to => 'project_module_vocabulary#update_attributes_vocab', :as => 'update_attributes_vocab'

  get 'project_module/:id/edit_project_module_user' , :to => 'project_module_user#edit_project_module_user', :as => 'edit_project_module_user'
  post 'project_module/:id/update_project_module_user' , :to => 'project_module_user#update_project_module_user', :as => 'update_project_module_user'
  post 'project_module/:id/remove_project_module_user/:user_id' , :to => 'project_module_user#remove_project_module_user', :as => 'remove_project_module_user'

  get 'project_exporters', :to => 'project_exporter#index', :as => 'project_exporters'
  get 'project_exporters/new', :to => 'project_exporter#new', :as => 'new_project_exporter'
  post 'project_exporters/new', :to => 'project_exporter#create', :as => 'new_project_exporter'
  post 'project_exporter/:key/update', :to => 'project_exporter#update', :as => 'update_project_exporter'
  post 'project_exporter/:key/delete', :to => 'project_exporter#delete', :as => 'delete_project_exporter'

  get 'android/modules', :to => 'android#project_modules', :as => 'android_project_modules'

  get 'android/module/:key/settings_info', :to => 'android#settings_info', :as => 'android_settings_info'
  get 'android/module/:key/settings_download', :to => 'android#settings_download', :as => 'android_settings_download'

  get 'android/module/:key/db_info', :to => 'android#db_info', :as => 'android_project_module_db_info'
  get 'android/module/:key/db_download', :to => 'android#db_download', :as => 'android_project_module_db_download'
  post 'android/module/:key/db_upload', :to => 'android#db_upload', :as => 'android_project_module_db_upload'

  get 'android/module/:key/data_files_info', :to => 'android#data_files_info', :as => 'android_data_files_info'
  get 'android/module/:key/data_file_download', :to => 'android#data_file_download', :as => 'android_data_file_download'
  post 'android/module/:key/data_file_upload', :to => 'android#data_file_upload', :as => 'android_data_file_upload'

  get 'android/module/:key/server_files_info', :to => 'android#server_files_info', :as => 'android_server_files_info'
  post 'android/module/:key/server_file_upload', :to => 'android#server_file_upload', :as => 'android_server_file_upload'

  get 'android/module/:key/app_files_info', :to => 'android#app_files_info', :as => 'android_app_files_info'
  get 'android/module/:key/app_file_download', :to => 'android#app_file_download', :as => 'android_app_file_download'
  post 'android/module/:key/app_file_upload', :to => 'android#app_file_upload', :as => 'android_app_file_upload'

  get 'thumbnail', :to => 'project_module_entity#thumbnail', :as => 'thumbnail'

  get 'server/update', :to => 'server#check_for_updates', :as => 'update_server'
  post 'server/update', :to => 'server#update', :as => 'update_server'
  get 'server/check_updated', :to => 'server#check_updated', :as => 'check_server_updated'
  post 'server/restart', :to => 'server#restart', :as => 'restart_server'

  root :to => 'pages#home'

  get 'pages/home'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserBreadCrumbs
  before_filter :crumbs
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    page_crumbs :pages_home, :users_index

    @users = User.all
  end

  def show
    page_crumbs :pages_home, :users_index, :users_show
  end

  def admin

  end

  def access_requests
    @users = User.pending_approval
  end

  def deactivate
    if !@user.check_number_of_superusers(params[:id], current_user.id)
      redirect_to(@user, :alert => "You cannot deactivate this account as it is the only account with superuser privileges.")
    else
      @user.deactivate
      redirect_to(@user, :notice => "The user has been deactivated.")
    end
  end

  def activate
    @user.activate
    redirect_to(@user, :notice => "The user has been activated.")
  end

  def reject
    @user.reject_access_request
    @user.destroy
    redirect_to(access_requests_users_path, :notice => "The access request for #{@user.email} was rejected.")
  end

  def reject_as_spam
    @user.reject_access_request
    redirect_to(access_requests_users_path, :notice => "The access request for #{@user.email} was rejected and this email address will be permanently blocked.")
  end

  def edit_role
    page_crumbs :pages_home, :users_index, :users_show, :users_edit_role

    if @user == current_user
      flash.now[:alert] = "You are changing the role of the user you are logged in as."
    elsif @user.rejected?
      redirect_to(users_path, :alert => "Role can not be set. This user has previously been rejected as a spammer.")
    end
    @roles = Role.by_name
  end

  def edit_approval
    @roles = Role.by_name
  end

  def update_role
    if params[:user][:role_id].blank?
      redirect_to(edit_role_user_path(@user), :alert => "Please select a role for the user.")
    else
      @user.role_id = params[:user][:role_id]
      if !@user.check_number_of_superusers(params[:id], current_user.id)
        redirect_to(edit_role_user_path(@user), :alert => "Only one superuser exists. You cannot change this role.")
      elsif @user.save
        redirect_to(@user, :notice => "The role for #{@user.email} was successfully updated.")
      end
    end
  end

  def approve
    if !params[:user][:role].blank?
      @user.role_id = params[:user][:role]
      @user.save
      @user.approve_access_request

      redirect_to(access_requests_users_path, :notice => "The access request for #{@user.email} was approved.")
    else
      redirect_to(edit_approval_user_path(@user), :alert => "Please select a role for the user.")
    end
  end

  def new
    page_crumbs :pages_home, :users_index, :users_add

    @user = User.new
  end

  def create
    page_crumbs :pages_home, :users_index, :users_add

    @user = User.new(params[:user])
    if @user.valid?
      @user.activate
      @user.role = Role.find_by_name('user')
      @user.save

      flash[:notice] = "New user created."
      redirect_to :users
    else
      flash[:error] = "Please correct the errors in this form."
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    if user
      if current_user.id == user.id
        flash[:error] = "Cannot delete yourself."
      else
        user.destroy
        flash[:notice] = "User deleted."
      end
    else
      flash[:error] = "Cannot find user."
    end
    redirect_to :users
  end

  def edit_details
    page_crumbs :pages_home, :users_index, :users_show, :users_edit_details

    @user = User.find(params[:id])
  end

  def update_details
    page_crumbs :pages_home, :users_index, :users_show, :users_edit_details

    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])
    if @user.valid?
      @user.save
      flash[:notice] = "Account details have been successfully updated."
      redirect_to users_path
    else
      flash[:error] = "Please correct the errors in this form."
      render 'edit_details'
    end
  end

  def change_password
    page_crumbs :pages_home, :users_index, :users_show, :users_edit_password

    @user = User.find(params[:id])
  end

  def save_password
    page_crumbs :pages_home, :users_index, :users_show, :users_edit_password

    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])
    if @user.valid?
      @user.save
      flash[:notice] = "Password has been updated."
      redirect_to users_path
    else
      flash[:error] = "Please correct the errors in this form."
      render 'change_password'
    end
  end

end

app/views/users/access_requests.html.haml
- title 'Access Requests'
= breadcrumbs
%table#access_requests.table.table-bordered.table-striped.table-condensed
  %tr
    %th First name
    %th Last name
    %th Email
    %th Actions
  - @users.each do |user|
    %tr{:class => cycle('field_bg', 'field_nobg')}
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td
        - if can?(:approve, user) then
          = link_to "Approve", edit_approval_user_path(user), :id => "approve_#{user.id}"
        - if can?(:reject, user) then
          = link_to "Reject", reject_user_path(user), :method => :put, :id => "reject_#{user.id}"
          = link_to "Reject as Spam", reject_as_spam_user_path(user), :method => :put, :id => "reject_as_spam_#{user.id}"
        = link_to "View Details", user, :id => "view_#{user.id}"

app/views/users/admin.html.haml
- title 'User Management'
= breadcrumbs
- if can?(:read, User)
  = link_to "List Approved Users", users_path, :class => "button"
- if can?(:access_requests, User)
  = link_to "View Access Requests", access_requests_users_path, :class => "button"

app/views/users/change_password.html.haml
- title "Change Password"
= breadcrumbs
= simple_form_for(@user, :url => save_password_user_path(@user), :html => { :method => :put }) do |f|
  = render "shared/error_messages", :target => @user
  = f.input :password, :label => "New password:", :required => true
  = f.input :password_confirmation, :label => "Confirm new password:",
  :hint => "Password must be between 6-20 characters long and contain at least one uppercase letter, one lowercase letter, one digit and one symbol.", :required => true
  .form-actions
    = link_to "<i class='icon-arrow-left'></i> Cancel".html_safe, user_path(@user), :class => "btn"
    = f.submit "Update", :class => "btn btn-inverse"

app/views/users/edit_approval.html.haml
- title "Select Role For #{@user.email}"
= breadcrumbs
= simple_form_for(@user, :url => approve_user_path(@user)) do |f|
  = render "shared/error_messages", :target => @user
  .field
    = f.input :role, :collection => @roles
  .form-actions
    = f.submit "Approve", :class => 'btn btn-inverse'
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, access_requests_users_path, :class => "btn"

app/views/users/edit_details.html.haml
- title "Edit Account Details"
= breadcrumbs
= simple_form_for(@user, :url => update_details_user_path(@user), :html => { :method => :put }) do |f|
  = render "shared/error_messages", :target => @user
  = f.input :first_name , :label => "First Name:"
  = f.input :last_name  , :label => "Last Name:"
  .form-actions
    = link_to "<i class='icon-arrow-left'></i> Cancel".html_safe, user_path(@user), :class => "btn"
    = f.submit "Update", :class => "btn btn-inverse"

app/views/users/edit_role.html.haml
- title "Edit Role For #{@user.email}"
= breadcrumbs
= simple_form_for(@user, :url => update_role_user_path(@user)) do |f|
  = render "shared/error_messages", :target => @user
  = f.input :role_id, :collection => @roles
  .form-actions
    = f.submit "Save", :class => 'btn btn-inverse'
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, @user, :class => "btn"

app/views/users/index.html.haml
- title 'Listing Users'
= breadcrumbs
- if current_user.admin?
  .well
    %h3 User Actions
    .btn-group
      = link_to "Add User", new_user_path, :class => 'btn btn-inverse'
%table#users.table.table-bordered.table-striped.table-condensed
  %tr
    %th First name
    %th Last name
    %th Email
    %th Role
    %th Last signed in
    %th Actions
  - @users.each do |user|
    %tr{:class => cycle('field_bg', 'field_nobg')}
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td= user.role.name if user.role
      %td
        - if user.last_sign_in_at.nil?
          Never logged in
        - else
          = user.last_sign_in_at.localtime.strftime("%d/%m/%Y %I:%M%p")
      %td
        = link_to "View Details", user, :id => "view_#{user.id}"
        - if can?(:edit_user, user)
          = link_to 'Edit role', edit_role_user_path(user), :id => "edit_role_#{user.id}"
        - if can?(:destroy, user) and current_user.id != user.id
          = link_to 'Delete', user, :id => "delete_#{user.id}", :method => :delete, :confirm => "Are you sure you want to delete user #{user.first_name} #{user.last_name}?"

app/views/users/new.html.haml
- title "Add User"
= breadcrumbs
= simple_form_for(@user) do |f|
  = f.label :first_name, "First Name:"
  = f.text_field :first_name
  = f.error :first_name
  = f.label :last_name, "Last Name:"
  = f.text_field :last_name
  = f.error :last_name
  = f.label :email, "Email:"
  = f.text_field :email
  = f.error :email
  = f.label :password, "Password:"
  = f.password_field :password
  = f.error :password
  = f.label :password_confirmation, "Password Confirmation:"
  = f.password_field :password_confirmation
  = f.error :password_confirmation
  .form-actions
    = f.submit "Submit", :class => 'btn btn-inverse'
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, users_path, :class => "btn"

app/views/users/show.html.haml
- title 'User Details'
= breadcrumbs
#userdetails
  %table.table.table-bordered.table-striped.table-condensed
    %tr
      %th First name
      %td= @user.first_name
    %tr
      %th Last name
      %td= @user.last_name
    %tr
      %th Email
      %td= @user.email
    %tr
      %th Role
      %td= @user.role ? @user.role.name : ""
    %tr
      %th Last signed in
      %td= @user.last_sign_in_at ? @user.last_sign_in_at.localtime.strftime("%d/%m/%Y %I:%M%p") : "Never logged in"
= link_to "<i class='icon-arrow-left'></i> Back".html_safe, users_path, :class => "btn"
- if @user.id != current_user.id and can?(:edit_user, @user)
  = link_to 'Edit Details', edit_details_user_path(@user), :class => 'btn btn-inverse'
  = link_to 'Change Password', change_password_user_path(@user), :class => 'btn btn-inverse'
- if can?(:edit_user, @user)
  = link_to 'Edit Role', edit_role_user_path(@user), :class => 'btn btn-inverse'