config/routes.rb
FaimsWeb::Application.routes.draw do
  devise_for :users, controllers: {passwords: 'user_passwords'}
  devise_scope :user do
    get '/users/profile', :to => 'user_registers#profile'
    get '/users/edit', :to => 'user_registers#edit'
    put '/users/update', :to => 'user_registers#update'
    get '/users/edit_password', :to => 'user_registers#edit_password' #allow users to edit their own password
    put '/users/update_password', :to => 'user_registers#update_password' #allow users to edit their own password
    get '/users/password/forgot', :to => 'user_passwords#forgot_password', :as => 'forgot_user_password'
  end

  resources :users, :only => [:show, :new, :create, :destroy] do

    collection do
      get :index
    end

    member do
      get :edit_role
      put :update_role
      get :edit_details
      put :update_details
      get :change_password
      put :save_password
    end
  end

  get 'project_modules', :to => 'project_modules#index', :as => 'project_modules'
  post 'project_modules', :to => 'project_modules#create', :as => 'project_modules'
  get 'project_modules/new', :to => 'project_modules#new', :as => 'new_project_module'
  get 'project_modules/upload_project_module', :to => 'project_modules#upload_project_module', :as => 'upload_project_module'
  post 'project_modules/upload_new_project_module', :to => 'project_modules#upload_new_project_module', :as => 'upload_new_project_module'
  get 'project_modules/deleted', :to => 'project_modules#list_deleted_modules', :as => 'list_deleted_modules'
  post 'project_modules/restore', :to => 'project_modules#restore_project_module', :as => 'restore_project_module'
  get 'project_modules/:id', :to => 'project_modules#show', :as => 'project_module'

  get 'project_modules/:id/edit_project_module', :to => 'project_modules#edit_project_module', :as => 'edit_project_module'
  post 'project_modules/:id/update_project_module', :to => 'project_modules#update_project_module', :as => 'update_project_module'
  delete 'project_modules/:id/delete_project_module', :to => 'project_modules#delete_project_module', :as => 'delete_project_module'

  get 'project_modules/:id/archive_project_module', :to => 'project_modules#archive_project_module', :as => 'archive_project_module'
  get 'project_modules/:id/download_project_module', :to => 'project_modules#download_project_module', :as => 'download_project_module'
  get 'project_modules/:id/check_archive_status', :to => 'project_modules#check_archive_status', :as => 'check_archive_status'
  get 'project_modules/:id/export_project_module', :to => 'project_modules#export_project_module', :as => 'export_project_module'
  post 'project_modules/:id/export_project_module', :to => 'project_modules#run_export_project_module', :as => 'run_export_project_module'
  get 'project_modules/:id/check_export_status', :to => 'project_modules#check_export_status', :as => 'check_export_status'
  get 'project_modules/:id/export_project_module/results', :to => 'project_modules#show_export_results', :as => 'show_export_results'
  get 'project_modules/:id/export_project_module/results/download_file', :to => 'project_modules#download_export_file', :as => 'download_export_file'

  get 'project_modules/:id/download_attached_file', :to => 'project_modules#download_attached_file', :as => 'download_attached_file'

  get 'project_modules/:id/file_list', :to => 'project_module_file#file_list', :as => 'project_module_file_list'
  get 'project_modules/:id/download_file', :to => 'project_module_file#download_file', :as => 'download_project_module_file'
  post 'project_modules/:id/upload_file', :to => 'project_module_file#upload_file', :as => 'upload_project_module_file'
  post 'project_modules/:id/create_dir', :to => 'project_module_file#create_dir', :as => 'project_module_create_dir'
  match 'project_modules/:id/delete_file', :to => 'project_module_file#delete_file', :as => 'delete_project_module_file'
  post 'project_modules/:id/batch_upload_file', :to => 'project_module_file#batch_upload_file', :as => 'batch_upload_file'

  get 'project_modules/:id/search_arch_ent_records/', :to => 'project_module_entity#search_arch_ent_records', :as => 'search_arch_ent_records'
  get 'project_modules/:id/delete_arch_ent_records/:uuid', :to => 'project_module_entity#delete_arch_ent_records', :as => 'delete_arch_ent_records'
  get 'project_modules/:id/restore_arch_ent_records/:uuid', :to => 'project_module_entity#restore_arch_ent_records', :as => 'restore_arch_ent_records'
  get 'project_modules/:id/edit_arch_ent_records/:uuid', :to => 'project_module_entity#edit_arch_ent_records', :as => 'edit_arch_ent_records'
  get 'project_modules/:id/get_arch_ent_record_data/:uuid', :to => 'project_module_entity#get_arch_ent_record_data', :as => 'get_arch_ent_record_data'
  post 'project_modules/:id/upload_arch_ent_attribute_file/:uuid', :to => 'project_module_entity#upload_arch_ent_attribute_file', :as => 'upload_arch_ent_attribute_file'
  post 'project_modules/:id/batch_edit_arch_ent_records/:uuid', :to => 'project_module_entity#batch_update_arch_ent_records', :as => 'batch_update_arch_ent_records'
  post 'project_modules/:id/batch_delete_related_ents/:uuid', :to => 'project_module_entity#batch_delete_related_ents', :as => 'batch_delete_related_ents'
  post 'project_modules/:id/batch_restore_related_ents/:uuid', :to => 'project_module_entity#batch_restore_related_ents', :as => 'batch_restore_related_ents'
  get 'project_modules/:id/show_arch_ent_history/:uuid', :to => 'project_module_entity#show_arch_ent_history', :as => 'show_arch_ent_history'
  post 'project_modules/:id/revert_arch_ent_to_timestamp/:uuid', :to => 'project_module_entity#revert_arch_ent_to_timestamp', :as => 'revert_arch_ent_to_timestamp'
  get 'project_modules/:id/compare_arch_ents', :to => 'project_module_entity#compare_arch_ents', :as => 'compare_arch_ents'
  post 'project_modules/:id/batch_delete_arch_ents', :to => 'project_module_entity#batch_delete_arch_ents', :as => 'batch_delete_arch_ents'
  post 'project_modules/:id/batch_restore_arch_ents', :to => 'project_module_entity#batch_restore_arch_ents', :as => 'batch_restore_arch_ents'
  post 'project_modules/:id/merge_arch_ents', :to => 'project_module_entity#merge_arch_ents', :as => 'merge_arch_ents'

  get 'project_modules/:id/list_attributes_with_vocab', :to => 'project_module_vocabulary#list_attributes_with_vocab', :as => 'list_attributes_with_vocab'
  post 'project_modules/:id/update_attributes_vocab', :to => 'project_module_vocabulary#update_attributes_vocab', :as => 'update_attributes_vocab'

  get 'project_module/:id/edit_project_module_user' , :to => 'project_module_user#edit_project_module_user', :as => 'edit_project_module_user'
  post 'project_module/:id/update_project_module_user' , :to => 'project_module_user#update_project_module_user', :as => 'update_project_module_user'
  post 'project_module/:id/remove_project_module_user/:user_id' , :to => 'project_module_user#remove_project_module_user', :as => 'remove_project_module_user'

  get 'project_exporters', :to => 'project_exporter#index', :as => 'project_exporters'
  get 'project_exporters/new', :to => 'project_exporter#new', :as => 'new_project_exporter'
  post 'project_exporters/new', :to => 'project_exporter#create', :as => 'new_project_exporter'
  post 'project_exporter/:key/update', :to => 'project_exporter#update', :as => 'update_project_exporter'
  post 'project_exporter/:key/delete', :to => 'project_exporter#delete', :as => 'delete_project_exporter'

  get 'android/modules', :to => 'android#project_modules', :as => 'android_project_modules'

  get 'android/module/:key/settings_info', :to => 'android#settings_info', :as => 'android_settings_info'
  get 'android/module/:key/settings_download', :to => 'android#settings_download', :as => 'android_settings_download'

  get 'android/module/:key/db_info', :to => 'android#db_info', :as => 'android_project_module_db_info'
  get 'android/module/:key/db_download', :to => 'android#db_download', :as => 'android_project_module_db_download'
  post 'android/module/:key/db_upload', :to => 'android#db_upload', :as => 'android_project_module_db_upload'

  get 'android/module/:key/data_files_info', :to => 'android#data_files_info', :as => 'android_data_files_info'
  get 'android/module/:key/data_file_download', :to => 'android#data_file_download', :as => 'android_data_file_download'
  post 'android/module/:key/data_file_upload', :to => 'android#data_file_upload', :as => 'android_data_file_upload'

  get 'android/module/:key/server_files_info', :to => 'android#server_files_info', :as => 'android_server_files_info'
  post 'android/module/:key/server_file_upload', :to => 'android#server_file_upload', :as => 'android_server_file_upload'

  get 'android/module/:key/app_files_info', :to => 'android#app_files_info', :as => 'android_app_files_info'
  get 'android/module/:key/app_file_download', :to => 'android#app_file_download', :as => 'android_app_file_download'
  post 'android/module/:key/app_file_upload', :to => 'android#app_file_upload', :as => 'android_app_file_upload'

  get 'thumbnail', :to => 'project_module_entity#thumbnail', :as => 'thumbnail'

  get 'server/update', :to => 'server#check_for_updates', :as => 'update_server'
  post 'server/update', :to => 'server#update', :as => 'update_server'
  get 'server/check_updated', :to => 'server#check_updated', :as => 'check_server_updated'
  post 'server/restart', :to => 'server#restart', :as => 'restart_server'

  root :to => 'pages#home'

  get 'pages/home'

end

app/views/project_modules/_checkbox.html.haml
- @checks.each do |check|
  .checkbox
    = @form.check_box("#{@label}:#{check}", {}, "true", "false")
    = @form.label("#{@label}:#{check}", check, class: "checkbox inline")

app/views/project_modules/edit_project_module.html.haml
-title 'Edit Module'
= breadcrumbs
.container
  = simple_form_for @project_module, :url => update_project_module_path, :class =>"span12", :method => "post" do|f|
    .row-fluid
      .settings.span6
        .step
          .step-body.span12
            %h4 Static Data
            = f.label :name, "Module Name:"
            = f.text_field :name, :value => @name, :class => "input-block-level"
            = f.error :name
            %p
            = f.label :version, 'Module Version:'
            = f.text_field :version, :value => @version, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :srid, 'Module SRID:'
            = f.select :srid, @spatial_list, :selected => @srid, :class => "input-block-level"
            %p
            = f.label :season, "Module Year:"
            = f.text_field :season, :value => @season, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :description, "Project Description:"
            = f.text_area :description, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @description, :placeholder => "instruction here..."
            %p
            = f.label :permit_no, "Permit No:"
            = f.text_field :permit_no, :value => @permit_no, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :permit_holder, "Permit Holder:"
            = f.text_area :permit_holder, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @permit_holder, :placeholder => "instruction here..."
            %p
            = f.label :permit_issued_by, 'Permit Issued by:'
            = f.text_field :permit_issued_by, :value => @permit_issued_by, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :permit_type, 'Permit Type:'
            = f.text_field :permit_type, :value => @permit_type, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :contact_address, "Contact and Address:"
            = f.text_area :contact_address, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @contact_address, :placeholder => "instruction here..."
            %p
            = f.label :participant, "Participants:"
            = f.text_area :participant, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @participant, :placeholder => "instruction here..."
            %p
            = f.label :copyright_holder, 'Copyright Holder:'
            = f.text_field :copyright_holder, :value => @copyright_holder, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :client_sponsor, 'Client/Sponsor:'
            = f.text_field :client_sponsor, :value => @client_sponsor, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :land_owner, 'Land Owner:'
            = f.text_field :land_owner, :value => @land_owner, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.input :has_sensitive_data, :checked => @has_sensitive_data, :as => :radio_buttons, :label => 'Will this Module contain sensitive data?'
      .upload.span6
        .well
          %h4 Upload User Interface Schema
          = f.hidden_field :tmpdir, :value => @tmpdir
          - if session[:ui_schema]
            %span.uploaded-inline UI Schema Uploaded!
          - else
            = f.label :ui_schema, 'UI Schema:'
            = f.file_field :ui_schema
            = f.error :ui_schema
        .well
          %h4 Upload Validation Schema
          - if session[:validation_schema]
            %span.uploaded-inline Validation Schema Uploaded!
          - else
            = f.label :validation_schema, 'Validation Schema:'
            = f.file_field :validation_schema
            = f.error :validation_schema
        .well
          %h4 Upload User Interface Logic
          - if session[:ui_logic]
            %span.uploaded-inline UI Logic Uploaded!
          - else
            = f.label :ui_logic, 'UI Logic:'
            = f.file_field :ui_logic
            = f.error :ui_logic
        .well
          %h4 Upload Arch16n file
          - if session[:arch16n]
            %span.uploaded-inline Arch16n Uploaded!
          - else
            = f.label :arch16n, 'Arch16n:'
            = f.file_field :arch16n
            = f.error :arch16n
        .well
          %h4 Upload CSS file
          - if session[:css_style]
            %span.uploaded-inline CSS Uploaded!
          - else
            = f.label :css_style, 'CSS:'
            = f.file_field :css_style
            = f.error :css_style
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, project_module_path(@project_module), :class => 'btn'
      = f.submit "Update", :class => "btn btn-inverse", :id => "update-project-module-setting-btn"

app/views/project_modules/edit_project_module_setting.html.haml
- title @project_module_setting['name']
= breadcrumbs
.container
  = simple_form_for @project_module, :url => update_project_module_setting_path, :class =>"span12", :method => "post" do|f|
    %h4 Static Data
    = f.label :name, "Module Name:"
    = f.text_field :name, :value => @project_module.name, :class => "input-block-level"
    = f.error :name
    %p
    = f.label :season, 'Module SRID:'
    = f.select :srid, @spatial_list, :selected => @project_module_setting['srid'], :class => "input-block-level"
    %p
    = f.label :season, "Module Season:"
    = f.text_field :season, :value => @project_module_setting['season'], :class => "input-block-level"
    %p
    = f.label :description, "Project Description:"
    = f.text_area :description, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @project_module_setting['description']
    %p
    = f.label :permit_no, "Permit No:"
    = f.text_field :permit_no, :value => @project_module_setting['permit_no'], :class => "input-block-level"
    %p
    = f.label :permit_holder, "Permit Holder:"
    = f.text_area :permit_holder, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @project_module_setting['permit_holder']
    %p
    = f.label :contact_address, "Contact and Address:"
    = f.text_area :contact_address, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @project_module_setting['contact_address']
    %p
    = f.label :participant, "Participants:"
    = f.text_area :participant, :size => "40x5", :class => 'project_module-textarea input-block-level', :value => @project_module_setting['participant']
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, project_module_path(@project_module), :class => 'btn'
      = f.submit "Update", :class => "btn btn-inverse", :id => "update-project-module-setting-btn"

app/views/project_modules/export_project_module.html.haml
-title 'Export Module'
= breadcrumbs

%input{:type => 'hidden', :value => check_export_status_path(@project_module), :id=> 'check-export'}

= collection_select("select", "exporter", @exporters, :key, :name, {:prompt => "Please select an exporter"})
.well
  - @exporters.each do |exporter|
    - config = exporter.get_config_json
    %div.exporter_interface{:id => exporter.key}
      = form_for(:exporter_interface, url: run_export_project_module_path, :method => :post) do |f|
        = hidden_field_tag("exporter_key", exporter.key)
        - if !config["interface"].nil?
          - config["interface"].each do |item|
            = render_exporter_interface_label(item, f)
            = render_exporter_interface_item(item, f)
        - else
          No interface to display for this exporter
          %br
        %br
        = submit_tag "Export", :class => 'btn-primary btn', :id => "export_module_#{exporter.key}"

#loading.hidden.indicator
  = image_tag "loading.gif"
  %p
    %span Exporting Module


:javascript

  $(document).ready(function () {
    $('.exporter_interface').hide()
    $('#select_exporter').find('option:first').attr('selected', 'selected')
  });

  $('#select_exporter').change(function() {
    $('.exporter_interface').hide()
    chosen = $('#select_exporter').val()
    if(chosen != "") {
      $('#' + chosen).show()
    }
  });

app/views/project_modules/index.html.haml
- title "Modules"
= breadcrumbs
.well
  = link_to "<i class='icon-pencil icon-white'></i> Create Module".html_safe, new_project_module_path, :class => "btn btn-inverse"
  = link_to "<i class='icon-upload'></i> Upload Module".html_safe, upload_project_module_path, :class => "btn"
.clear
- if @project_modules
  %table.table
    %tr
      %th No.
      %th Name
      %th Created
    - index = 0
    - for project_module in @project_modules
      - index = index + 1
      %tr
        %td
          = index.to_s + "."
        %td
          %a.project_module{href:project_module_path(project_module)}
            = project_module.name
        %td
          = project_module.created_at.localtime.strftime("%d/%m/%Y %I:%M%p")

app/views/project_modules/list_deleted_modules.html.haml
- title "Deleted Modules"
= breadcrumbs
.clear
- if @project_modules
  %table.table#project-modules
    %tr
      %th No.
      %th Name
      %th Created
      %th
    - index = 0
    - for project_module in @project_modules
      - index = index + 1
      %tr
        %td
          = index.to_s + "."
        %td.project-name
          = project_module.name
        %td
          = project_module.created_at.localtime.strftime("%d/%m/%Y %I:%M%p")
        %td.restore-btn
          = button_to "Restore", { action: :restore_project_module, controller: :project_modules, restore_id: project_module.id }, method: :post, class: 'btn'

app/views/project_modules/list_typed_arch_ent_records.html.haml
- title @project_module.name + " - Archaeological Entity Records"
= breadcrumbs
.content
  - if (!@uuid.empty?)
    %input{:type => 'hidden', :value => add_entity_to_compare_path(@project_module), :id => 'add-entity'}
    %input{:type => 'hidden', :value => remove_entity_to_compare_path(@project_module), :id => 'remove-entity'}
    %form{:method => 'post', :id => 'compare'}
      %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
      - if session[:values]
        - session[:values].length.times do |i|
          %input{:type => 'hidden', :value => session[:values][i-1], :name => 'ids[]', :id => session[:values][i-1]}
          %input{:type => 'hidden', :value => session[:identifiers][i-1], :name => 'identifiers[]', :id => session[:values][i-1]}
          %input{:type => 'hidden', :value => session[:timestamps][i-1], :name => 'timestamps[]', :id => session[:values][i-1]}
      %p
        = render :partial => 'edit_arch_ent_record', :locals => {values: session[:values]}
  -else
    %p No Records Found
  .form-actions
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, list_arch_ent_records_path(@project_module), :class => 'btn'
    = link_to "Compare" ,compare_arch_ents_path(@project_module), :id => 'compare-button', :class => 'btn btn-inverse'
    - if session[:show_deleted].nil?
      = link_to "Show Deleted", '#', :id => 'show-hide-deleted', :class => 'btn btn-inverse'
    - else
      = link_to "Hide Deleted", '#', :id => 'show-hide-deleted', :class => 'btn'
    %form{:action => list_typed_arch_ent_records_path, :method => "get", :id => 'show-hide-deleted-form'}
      %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
      %input{:type => 'hidden', :value => session[:type], :name => 'type'}
      - if session[:show_deleted].nil?
        %input{:type => 'hidden', :value => 'true', :name => 'show_deleted'}

app/views/project_modules/new.html.haml
- title 'Create Module'
= breadcrumbs
.container
  = simple_form_for @project_module, :url => project_modules_path, :method => 'post', :multipart => true do |f|
    = f.hidden_field :tmpdir, :value => @tmpdir
    .row-fluid
      .settings.span6
        .step
          .step-body.span12
            %h4 Static Data
            = f.label :name, 'Module Name:', :class => "required"
            = f.text_field :name, :class => "input-block-level"
            = f.error :name
            %p
            = f.label :version, 'Module Version:'
            = f.text_field :version, :value => @version, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :season, 'Module SRID:'
            = f.select :srid, @spatial_list, :selected => (@srid.blank? ? ProjectModule::DEFAULT_SRID : @srid), :class => "input-block-level"
            %p
            = f.label :season, 'Module Year:'
            = f.text_field :season, :value => @season, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :description, 'Project Description:'
            = f.text_area :description, :size => '40x5', :class => 'project_module-textarea span12', :value => @description, :placeholder => "instruction here..."
            %p
            = f.label :permit_no, 'Permit No:'
            = f.text_field :permit_no, :value => @permit_no, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :permit_holder, 'Permit Holder:'
            = f.text_area :permit_holder, :size => '40x5', :class => 'project_module-textarea span12', :value => @permit_holder, :placeholder => "e.g. Doe, John; Smith, Jane"
            %p
            = f.label :permit_issued_by, 'Permit Issued by:'
            = f.text_field :permit_issued_by, :value => @permit_issued_by, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :permit_type, 'Permit Type:'
            = f.text_field :permit_type, :value => @permit_type, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :contact_address, 'Contact and Address:'
            = f.text_area :contact_address, :size => '40x5', :class => 'project_module-textarea span12', :value => @contact_address, :placeholder => "instruction here..."
            %p
            = f.label :participant, 'Participants:'
            = f.text_area :participant, :size => '40x5', :class => 'project_module-textarea span12', :value => @participant, :placeholder => "instruction here..."
            %p
            = f.label :copyright_holder, 'Copyright Holder:'
            = f.text_field :copyright_holder, :value => @copyright_holder, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :client_sponsor, 'Client/Sponsor:'
            = f.text_field :client_sponsor, :value => @client_sponsor, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.label :land_owner, 'Land Owner:'
            = f.text_field :land_owner, :value => @land_owner, :class => "input-block-level", :placeholder => "instruction here..."
            %p
            = f.input :has_sensitive_data, :checked => @has_sensitive_data, :as => :radio_buttons, :label => 'Will this Module contain sensitive data?'
      .upload.span6
        .well
          %h4 Upload Data Definition Schema
          - if session[:data_schema]
            %span.uploaded-inline Data Schema Uploaded!
          - else
            = f.label :data_schema, 'Data Schema:', :class => "required"
            = f.file_field :data_schema
            = f.error :data_schema
        .well
          %h4 Upload User Interface Schema
          - if session[:ui_schema]
            %span.uploaded-inline UI Schema Uploaded!
          - else
            = f.label :ui_schema, 'UI Schema:', :class => "required"
            = f.file_field :ui_schema
            = f.error :ui_schema
        .well
          %h4 Upload Validation Schema
          - if session[:validation_schema]
            %span.uploaded-inline Validation Schema Uploaded!
          - else
            = f.label :validation_schema, 'Validation Schema:'
            = f.file_field :validation_schema
            = f.error :validation_schema
        .well
          %h4 Upload User Interface Logic
          - if session[:ui_logic]
            %span.uploaded-inline UI Logic Uploaded!
          - else
            = f.label :ui_logic, 'UI Logic:', :class => "required"
            = f.file_field :ui_logic
            = f.error :ui_logic
        .well
          %h4 Upload Arch16n file
          - if session[:arch16n]
            %span.uploaded-inline Arch16n Uploaded!
          - else
            = f.label :arch16n, 'Arch16n:'
            = f.file_field :arch16n
            = f.error :arch16n
        .well
          %h4 Upload CSS file
          - if session[:css_style]
            %span.uploaded-inline CSS Uploaded!
          - else
            = f.label :css_style, 'CSS:'
            = f.file_field :css_style
            = f.error :css_style
    .form-actions
      = f.submit 'Submit', :class => 'btn btn-inverse', :id => 'submit-project-module-btn'
      = link_to 'Clear', new_project_module_path, :class => 'btn'

#loading.hidden.indicator
  = image_tag 'loading.gif'
  %p
    %span Creating Module

app/views/project_modules/show.html.haml
- title @project_module.name
= breadcrumbs

%input{:type => 'hidden', :value => check_archive_status_path(@project_module), :id=> 'check-archive'}
%input{:type => 'hidden', :value => download_project_module_path(@project_module), :id=> 'download-project-module'}

.well
  %h3 Module Actions
  .btn-group
    = link_to "Edit Module", edit_project_module_path(@project_module), :class => 'btn'
    = link_to "Edit Vocabulary", list_attributes_with_vocab_path(@project_module), :class => 'btn'
    = link_to "Edit Users", edit_project_module_user_path(@project_module), :class => 'btn'
  .btn-group
    = link_to "Upload Files", project_module_file_list_path(@project_module), :class => 'btn', :id => 'project-module-file-list-btn'
    = link_to "Download Module", archive_project_module_path(@project_module), :class => 'btn', :id => 'archive-project-module-btn'
    = link_to "Export Module", export_project_module_path(@project_module), :class => 'btn', :id => 'export-project-module-btn'
.well
  %h3 Module Details
  .btn-group
    = link_to "Search Entity Records", search_arch_ent_records_path(@project_module), :class => 'btn'
    =# link_to "Search Relationship Records", search_rel_records_path(@project_module), :class => 'btn'
.well
  %h3 Danger Zone
  .btn-group
    = link_to "Delete Module", delete_project_module_path(@project_module), :class => 'btn btn-danger', :method => :delete, confirm: "Are you sure you want to delete module?"
.form-actions
  = link_to "<i class='icon-arrow-left'></i> Back".html_safe, project_modules_path, :class => 'btn'

#loading.hidden.indicator
  = image_tag "loading.gif"
  %p
    %span Archiving Module

app/views/project_modules/show_export_results.html.haml
-title 'Export Module Results'
= breadcrumbs

.well
  - if @markup and !@markup.empty?
    = raw(@markup)
  - else
    Nothing to display
- if @has_download_file
  = link_to "Download file", download_export_file_path, :class => 'btn-primary btn'