config/routes.rb
FaimsWeb::Application.routes.draw do
  devise_for :users, controllers: {passwords: 'user_passwords'}
  devise_scope :user do
    get '/users/profile', :to => 'user_registers#profile'
    get '/users/edit', :to => 'user_registers#edit'
    put '/users/update', :to => 'user_registers#update'
    get '/users/edit_password', :to => 'user_registers#edit_password' #allow users to edit their own password
    put '/users/update_password', :to => 'user_registers#update_password' #allow users to edit their own password
    get '/users/password/forgot', :to => 'user_passwords#forgot_password', :as => 'forgot_user_password'
  end

  resources :users, :only => [:show, :new, :create, :destroy] do

    collection do
      get :index
    end

    member do
      get :edit_role
      put :update_role
      get :edit_details
      put :update_details
      get :change_password
      put :save_password
    end
  end

  get 'project_modules', :to => 'project_modules#index', :as => 'project_modules'
  post 'project_modules', :to => 'project_modules#create', :as => 'project_modules'
  get 'project_modules/new', :to => 'project_modules#new', :as => 'new_project_module'
  get 'project_modules/upload_project_module', :to => 'project_modules#upload_project_module', :as => 'upload_project_module'
  post 'project_modules/upload_new_project_module', :to => 'project_modules#upload_new_project_module', :as => 'upload_new_project_module'
  get 'project_modules/deleted', :to => 'project_modules#list_deleted_modules', :as => 'list_deleted_modules'
  post 'project_modules/restore', :to => 'project_modules#restore_project_module', :as => 'restore_project_module'
  get 'project_modules/:id', :to => 'project_modules#show', :as => 'project_module'

  get 'project_modules/:id/edit_project_module', :to => 'project_modules#edit_project_module', :as => 'edit_project_module'
  post 'project_modules/:id/update_project_module', :to => 'project_modules#update_project_module', :as => 'update_project_module'
  delete 'project_modules/:id/delete_project_module', :to => 'project_modules#delete_project_module', :as => 'delete_project_module'

  get 'project_modules/:id/archive_project_module', :to => 'project_modules#archive_project_module', :as => 'archive_project_module'
  get 'project_modules/:id/download_project_module', :to => 'project_modules#download_project_module', :as => 'download_project_module'
  get 'project_modules/:id/check_archive_status', :to => 'project_modules#check_archive_status', :as => 'check_archive_status'
  get 'project_modules/:id/export_project_module', :to => 'project_modules#export_project_module', :as => 'export_project_module'
  post 'project_modules/:id/export_project_module', :to => 'project_modules#run_export_project_module', :as => 'run_export_project_module'
  get 'project_modules/:id/check_export_status', :to => 'project_modules#check_export_status', :as => 'check_export_status'
  get 'project_modules/:id/export_project_module/results', :to => 'project_modules#show_export_results', :as => 'show_export_results'
  get 'project_modules/:id/export_project_module/results/download_file', :to => 'project_modules#download_export_file', :as => 'download_export_file'

  get 'project_modules/:id/download_attached_file', :to => 'project_modules#download_attached_file', :as => 'download_attached_file'

  get 'project_modules/:id/file_list', :to => 'project_module_file#file_list', :as => 'project_module_file_list'
  get 'project_modules/:id/download_file', :to => 'project_module_file#download_file', :as => 'download_project_module_file'
  post 'project_modules/:id/upload_file', :to => 'project_module_file#upload_file', :as => 'upload_project_module_file'
  post 'project_modules/:id/create_dir', :to => 'project_module_file#create_dir', :as => 'project_module_create_dir'
  match 'project_modules/:id/delete_file', :to => 'project_module_file#delete_file', :as => 'delete_project_module_file'
  post 'project_modules/:id/batch_upload_file', :to => 'project_module_file#batch_upload_file', :as => 'batch_upload_file'

  get 'project_modules/:id/search_arch_ent_records/', :to => 'project_module_entity#search_arch_ent_records', :as => 'search_arch_ent_records'
  get 'project_modules/:id/delete_arch_ent_records/:uuid', :to => 'project_module_entity#delete_arch_ent_records', :as => 'delete_arch_ent_records'
  get 'project_modules/:id/restore_arch_ent_records/:uuid', :to => 'project_module_entity#restore_arch_ent_records', :as => 'restore_arch_ent_records'
  get 'project_modules/:id/edit_arch_ent_records/:uuid', :to => 'project_module_entity#edit_arch_ent_records', :as => 'edit_arch_ent_records'
  get 'project_modules/:id/get_arch_ent_record_data/:uuid', :to => 'project_module_entity#get_arch_ent_record_data', :as => 'get_arch_ent_record_data'
  post 'project_modules/:id/upload_arch_ent_attribute_file/:uuid', :to => 'project_module_entity#upload_arch_ent_attribute_file', :as => 'upload_arch_ent_attribute_file'
  post 'project_modules/:id/batch_edit_arch_ent_records/:uuid', :to => 'project_module_entity#batch_update_arch_ent_records', :as => 'batch_update_arch_ent_records'
  post 'project_modules/:id/batch_delete_related_ents/:uuid', :to => 'project_module_entity#batch_delete_related_ents', :as => 'batch_delete_related_ents'
  post 'project_modules/:id/batch_restore_related_ents/:uuid', :to => 'project_module_entity#batch_restore_related_ents', :as => 'batch_restore_related_ents'
  get 'project_modules/:id/show_arch_ent_history/:uuid', :to => 'project_module_entity#show_arch_ent_history', :as => 'show_arch_ent_history'
  post 'project_modules/:id/revert_arch_ent_to_timestamp/:uuid', :to => 'project_module_entity#revert_arch_ent_to_timestamp', :as => 'revert_arch_ent_to_timestamp'
  get 'project_modules/:id/compare_arch_ents', :to => 'project_module_entity#compare_arch_ents', :as => 'compare_arch_ents'
  post 'project_modules/:id/batch_delete_arch_ents', :to => 'project_module_entity#batch_delete_arch_ents', :as => 'batch_delete_arch_ents'
  post 'project_modules/:id/batch_restore_arch_ents', :to => 'project_module_entity#batch_restore_arch_ents', :as => 'batch_restore_arch_ents'
  post 'project_modules/:id/merge_arch_ents', :to => 'project_module_entity#merge_arch_ents', :as => 'merge_arch_ents'

  get 'project_modules/:id/list_attributes_with_vocab', :to => 'project_module_vocabulary#list_attributes_with_vocab', :as => 'list_attributes_with_vocab'
  post 'project_modules/:id/update_attributes_vocab', :to => 'project_module_vocabulary#update_attributes_vocab', :as => 'update_attributes_vocab'

  get 'project_module/:id/edit_project_module_user' , :to => 'project_module_user#edit_project_module_user', :as => 'edit_project_module_user'
  post 'project_module/:id/update_project_module_user' , :to => 'project_module_user#update_project_module_user', :as => 'update_project_module_user'
  post 'project_module/:id/remove_project_module_user/:user_id' , :to => 'project_module_user#remove_project_module_user', :as => 'remove_project_module_user'

  get 'project_exporters', :to => 'project_exporter#index', :as => 'project_exporters'
  get 'project_exporters/new', :to => 'project_exporter#new', :as => 'new_project_exporter'
  post 'project_exporters/new', :to => 'project_exporter#create', :as => 'new_project_exporter'
  post 'project_exporter/:key/update', :to => 'project_exporter#update', :as => 'update_project_exporter'
  post 'project_exporter/:key/delete', :to => 'project_exporter#delete', :as => 'delete_project_exporter'

  get 'android/modules', :to => 'android#project_modules', :as => 'android_project_modules'

  get 'android/module/:key/settings_info', :to => 'android#settings_info', :as => 'android_settings_info'
  get 'android/module/:key/settings_download', :to => 'android#settings_download', :as => 'android_settings_download'

  get 'android/module/:key/db_info', :to => 'android#db_info', :as => 'android_project_module_db_info'
  get 'android/module/:key/db_download', :to => 'android#db_download', :as => 'android_project_module_db_download'
  post 'android/module/:key/db_upload', :to => 'android#db_upload', :as => 'android_project_module_db_upload'

  get 'android/module/:key/data_files_info', :to => 'android#data_files_info', :as => 'android_data_files_info'
  get 'android/module/:key/data_file_download', :to => 'android#data_file_download', :as => 'android_data_file_download'
  post 'android/module/:key/data_file_upload', :to => 'android#data_file_upload', :as => 'android_data_file_upload'

  get 'android/module/:key/server_files_info', :to => 'android#server_files_info', :as => 'android_server_files_info'
  post 'android/module/:key/server_file_upload', :to => 'android#server_file_upload', :as => 'android_server_file_upload'

  get 'android/module/:key/app_files_info', :to => 'android#app_files_info', :as => 'android_app_files_info'
  get 'android/module/:key/app_file_download', :to => 'android#app_file_download', :as => 'android_app_file_download'
  post 'android/module/:key/app_file_upload', :to => 'android#app_file_upload', :as => 'android_app_file_upload'

  get 'thumbnail', :to => 'project_module_entity#thumbnail', :as => 'thumbnail'

  get 'server/update', :to => 'server#check_for_updates', :as => 'update_server'
  post 'server/update', :to => 'server#update', :as => 'update_server'
  get 'server/check_updated', :to => 'server#check_updated', :as => 'check_server_updated'
  post 'server/restart', :to => 'server#restart', :as => 'restart_server'

  root :to => 'pages#home'

  get 'pages/home'

end

app/views/project_module_association/search_arch_ent_member.html.haml
- title @project_module.name + " - Search"
= breadcrumbs
.content
  %h2 Search Entity
  %p
  .search-arch-member
    %ul.tabs
      %li.search
        %form{:action => search_arch_ent_member_path, :method => "get"}
          %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
          %input{:type => 'hidden', :value => 0, :name => 'offset'}
          %input{:type => 'hidden', :value => session[:relntypeid], :name => 'relntypeid'}
          .input-append
            - if session[:query]
              %input{:type => 'text', :name => 'search_query', :value=> session[:search_query]}
            -else
              %input{:type => 'text', :name => 'search_query'}
            %input{:type => 'submit', :value => "Search", :class => 'btn'}
        - if !@uuid.nil? and !@uuid.empty?
          %form{:action => add_arch_ent_member_path(@project_module), :method => "post", id: 'add-arch-ent-form'}
            %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
            %input{:type => 'hidden', :name => 'relationshipid',:value => session[:relationshipid]}
            %input{:type => 'hidden', :name => 'relntypeid',:value => session[:relntypeid]}
            %input{:type => 'hidden', :name => 'verb'}
            .records
              - for uuids in @uuid
                %ul.inner
                  %input{:type => 'radio', :name=> 'uuid',:value => uuids[0]}
                  %li
                    %span
                      =uuids[1].to_s
          .paging.search
            = render :partial => 'shared/pagination'
        -else
          - if @status.eql?('init')
            %p Please enter keywords to search for a particular entity or leave the search empty to show all entities
          -else
            %p No Entities found
      %li.verb
        %h4 Entity Verb
        %label Verb (if required)
        .input-append
          %select{:id => 'select-verb'}
            - for verb in @verb
              %option{:value => verb[0].to_s.strip}
                =verb[0].to_s.strip
          %input{:type => 'button', :value=> 'Add Member', :id => 'add-arch-ent', :class => 'btn'}
  .form-actions
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, show_rel_members_path(@project_module,session[:relationshipid])+'?offset=0&relntypeid='+session[:relntypeid], :class => 'btn'

app/views/project_module_association/search_rel_association.html.haml
- title @project_module.name + " - Search"
= breadcrumbs
.content
  %h2 Search Relationship
  %p
  .search-arch-member
    %ul.tabs
      %li.search
        %form{:action => search_rel_association_path, :method => "get"}
          %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
          %input{:type => 'hidden', :value => 0, :name => 'offset'}
          .input-append
            - if session[:query]
              %input{:type => 'text', :name => 'search_query', :value=> session[:search_query]}
            -else
              %input{:type => 'text', :name => 'search_query'}
            %input{:type => 'submit', :value => "Search", :class => 'btn'}
        - if !@relationships.nil? and !@relationships.empty?
          %form{:action => add_rel_association_path(@project_module), :method => "post", id: 'add-rel-form'}
            %input{:type => 'hidden', :value => session[:authenticity_token], :name => 'authenticity_token'}
            %input{:type => 'hidden', :name => 'uuid', :value => session[:uuid]}
            %input{:type => 'hidden', :name => 'verb'}
            .records
              - for relationships in @relationships
                %ul.inner
                  %input{:type => 'radio', :name => 'relationshipid',:value => relationships[0]}
                  %input{:type => 'hidden', :name => 'typeid', :value => relationships[2], :src => get_verbs_for_rel_association_path(@project_module)}
                  %li
                    %span
                      =relationships[1].to_s
          .paging.search
            = render :partial => 'shared/pagination'
        -else
          - if @status.eql?('init')
            %p Please enter keywords to search for a particular relationship or leave the search empty to show all relationships
          -else
            %p No Relationships found
      %li.verb
        %h4 Relationship Verb
        %label Verb (if required)
        .input-append
          %select{:id => 'select-verb'}
          %input{:type => 'button', :value=> 'Add Member', :id => 'add-rel', :class => 'btn'}
  .form-actions
    = link_to "<i class='icon-arrow-left'></i> Back".html_safe, show_rel_association_path(@project_module,session[:uuid])+'?offset=0', :class => 'btn'

app/views/project_module_association/show_rel_association.html.haml
- title @project_module.name + " - Entity Relationship Associations"
= breadcrumbs
.content
  - if !@relationships.nil? and !@relationships.empty?
    .records
      %ul.inner
        - for relationships in @relationships
          %li
            %form.pull-left{:action => remove_rel_association_path(@project_module), :method => "post"}
              %input{ type: :hidden, name: :authenticity_token, value: session[:authenticity_token]}
              %input{ type: :hidden, name: :relationshipid, value: relationships[0]}
              %input{ type: :hidden, name: :uuid, value: session[:uuid]}
              .remove-member= link_to "<i class='ui-icon ui-icon-circle-minus'></i>".html_safe
            %a{:href => edit_rel_records_path(@project_module,relationships[0])}
              =relationships[1].to_s
          .clear
      .paging.search
        = render :partial => 'shared/pagination'
    %input{:type => 'button',:id => 'search-member', :value=> 'Add Member', :class => 'add-member btn', :src=> search_rel_association_path(@project_module,session[:uuid])}
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, edit_arch_ent_records_path(@project_module,session[:uuid]), :class => 'btn'
  -else
    %p No Members Found
    %input{:type => 'button',:id => 'search-member', :value=> 'Add Member', :class => 'add-member btn', :src=> search_rel_association_path(@project_module,session[:uuid])}
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, edit_arch_ent_records_path(@project_module,session[:uuid]), :class => 'btn'

app/views/project_module_association/show_rel_members.html.haml
- title @project_module.name + " - Relationship Entity Members"
= breadcrumbs
.content
  - if !@uuid.nil? and !@uuid.empty?
    .records
      %ul.inner
        - for uuids in @uuid
          %li
            %form.pull-left{:action => remove_arch_ent_member_path(@project_module), :method => "post"}
              %input{ type: :hidden, name: :authenticity_token, value: session[:authenticity_token]}
              %input{ type: :hidden, name: :relationshipid, value: session[:relationshipid]}
              %input{ type: :hidden, name: :relntypeid, value: session[:relntypeid]}
              %input{ type: :hidden, name: :uuid, value: uuids[0]}
              .remove-member= link_to "<i class='ui-icon ui-icon-circle-minus'></i>".html_safe
            %a{:href => edit_arch_ent_records_path(@project_module,uuids[0])}
              =uuids[1].to_s
          .clear
      .paging.search
        = render :partial => 'shared/pagination'
    %input{:type => 'button',:id => 'search-member', :value=> 'Add Member', :class => 'add-member btn', :src=> search_arch_ent_member_path(@project_module,session[:relationshipid])+"?relntypeid="+session[:relntypeid].to_s}
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, edit_rel_records_path(@project_module,session[:relationshipid]), :class => 'btn'
  -else
    %p No Members Found
    %input{:type => 'button',:id => 'search-member', :value=> 'Add Member', :class => 'add-member btn', :src=> search_arch_ent_member_path(@project_module,session[:relationshipid])+"?relntypeid="+session[:relntypeid].to_s}
    .form-actions
      = link_to "<i class='icon-arrow-left'></i> Back".html_safe, edit_rel_records_path(@project_module,session[:relationshipid]), :class => 'btn'